image: atlassian/default-image:2

pipelines:
  pull-requests:
    '**':
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - npm install
            - npm run build
            - zip myapp.zip -r build package.json package-lock.json ormconfig.js
          artifacts:
            - myapp.zip
      - step:
          name: "Deploy to Production"
          # Track production environments builds using deployments.
          deployment: production
          script:
            - pipe: atlassian/aws-elasticbeanstalk-deploy:0.5.0
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION_TBC
                APPLICATION_NAME: $APPLICATION_NAME_TBC
                ENVIRONMENT_NAME: $ENVIRONMENT_NAME_TBC
                VERSION_LABEL: $VERSION_LABEL
                S3_BUCKET: $S3_BUCKET_TBC
                DEBUG: 'true'
                ZIP_FILE: 'myapp.zip'